### ISSUE TITLE
Incorrect query string parameter for language

### ISSUE THREAD

**Issue by swapnilmarkhedkar** [codetriage/CodeTriage#1305]
The query string  ```?language_covid=``` reflects no changes. However, ```?language=``` yeilds the right result, but it is not used.

## Expected Behavior

![Screenshot from 2020-05-16 01-46-17](https://user-images.githubusercontent.com/34151176/82093144-33114300-9718-11ea-9c3c-89241b526618.png)
![Screenshot from 2020-05-16 01-46-38](https://user-images.githubusercontent.com/34151176/82093161-3e646e80-9718-11ea-9841-df0d4cced811.png)
![Screenshot from 2020-05-16 02-05-15](https://user-images.githubusercontent.com/34151176/82093942-bc754500-9719-11ea-9e38-d2447e151117.png)

## Current Behavior

![Screenshot from 2020-05-16 01-48-24](https://user-images.githubusercontent.com/34151176/82093330-8b484500-9718-11ea-9e1c-d500e3403685.png)
![Screenshot from 2020-05-16 02-04-34](https://user-images.githubusercontent.com/34151176/82093936-ba12eb00-9719-11ea-88fb-5aa8ccd5813c.png)

Additionally, changes are reflected in only the selected dropdown field, however, it must be shown for both the dropdowns  fields.

## Possible Solution

A quick fix would be changing  query string  ```?language_covid=``` to  ```?language=```

## Steps to Reproduce (for bugs)

1. Select a language from the dropdown

## Context

I was trying to narrow down to a language.

## Your Environment

* Browser Name and version: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Linux Mint 19.2 Cinnamon

## Additional request
It would be great if I could be assigned to work on this issue.

**Comment by schneems** [comment]
> It would be great if I could be assigned to work on this issue.

That would be great. Take a stab at it! Thanks for reporting this

**Comment by Cueball** [comment]
Came here to report what I think is the same issue, since I keep getting the email nags, but couldn't filter on projects where I might want to try to contribute.

Was going to add some more extended information on #1314 but then checked PRs and the PR above seems to solve an issue that's affected at least 2 people from filtering projects correctly [and consequently walking away until the next nag email arrives...come back, check, still broken, OK, try again later.]

That said, can say I don't understand the fix in #1307, but it *seems* to be an issue with a low-impact fix that's been known of for over a month now.

And sure - now I know I can tweak the URL to filter like I want, but I'd like to believe no-one thinks that's a good idea...

**Comment by schneems** [comment]
I've removed the covid part of the homepage for now.
