### ISSUE TITLE
Exercism is not interested in triaging efforts

### ISSUE THREAD

**Issue by scheals** [codetriage/CodeTriage#1768]
I started out with CodeTriage very recently and picked up [exercism as one of the repos](https://www.codetriage.com/exercism/exercism.io) to receive issues from. It seems that they are not interested in being listed on there as per [this comment I received](https://github.com/exercism/exercism/issues/6573#issuecomment-1423286854).

## Expected Behavior
- Only repos interested in triaging support are listed on the site.

## Current Behavior
- The [exercism repo](https://www.codetriage.com/exercism/exercism.io) is not interested in receiving support triaging but is listed on the site.

## Possible Solution
- Delist the repo from the site.
- When triaging, mention that the repo was listed on CodeTriage, so the maintainers can possibly share their stance on being listed there.
- Create a way to flag/tag repos that don't need help in some way so the users can relay such information to each other without requiring intervention from the CodeTriage maintainers.

**Comment by schneems** [comment]
> The [exercism repo](https://www.codetriage.com/exercism/exercism.io) is not interested in receiving support triaging but is listed on the site.

They have given a signal that this isn't maybe there are other repos out there with higher need and I think that's valid. I wouldn't go so far as to say that someone really committed and wanting to help this specific repo cannot find a way to do so in a way that also serves maintainer needs.

Other than the off topic bit about why you're there I actually think you incidentally raised a really good point about the README. The other maintainer gave it an eyes emoji and didn't mark it as off topic.

I think if I were to give you feedback on your initial response, I would suggest to add additional information:

- What you saw
- How you feel about it
- What you're wanting (in general)
- What you're asking the original poster for specifically

This is following the Non-violent communication (NVC) pattern, but could also be helpful here. Maybe an example comment could be:

"If I understand correctly you're asking about <blank>. From reading the README in this section <details> it seems like that might be better served in the <blank>. I'm wanting to help out. Forgive me if this isn't helpful"

This comment does a few things. It indicates your level of certainty. "If I understand correctly" it gives them details for why you think/feel that way "from reading" and finally instead of asking them to move it to a different repo, ask them for something smaller like validating that you're understanding the documentation correctly.

Then, while the maintainers still might have disregarded the suggestion to move the issue, they'll possibly have a new actionable issue of: update the documentation.

I know it might feel like a "failed" experiment, but 99% of the battle is finding ways to salvage the good from the bad and keep working to increase your context and confidence in what will be helpful. 

> @kotp is a project maintainer and one of Exercism's top contributors, so knows how things work very well here.

Oof. I generally recommend shadowing or lurking on a repo for awhile to see common patterns and behaviors. If you see another maintainer doing something you feel you can do too, then that's a good opportunity. You can also use that as an opportunity to build up context on a project.

Being aware of the main contributors already working on the project can be very helpful. Try to jump in when they're actively involved might actually slow them down. There's some subtle hints and clues if you don't have that context. Like the little "member" tag on the issue indicates they've got commit access to the repo and aren't just a random person. 

No one gets it all right the first time though.

> Only repos interested in triaging support are listed on the site.

CodeTriage is a tool that sends emails about issues. It doesn't know the social dynamics of a repo and it doesn't know why someone wants to get emails for that repo. Anyone can add any public repo for any reason. Even if a team states they're not in __need__ of additional triaging, if someone is committed, capable, and persistent then they might be able to spot gaps or needs that the current team does not.

I made a video about identifying opportunities as part of a broader contribution flow https://www.youtube.com/watch?v=5znQMEuHqc4.

Also, check out the "familiarity" section of my book if you've got access to it. There's also a free cheatsheet with the takeaways here https://howtoopensource.dev/downloads/how_to_open_source-cheatsheets.pdf. 

• What are ways to get more comfortable contributing to a project?
	◦ Look for written contribution guides.
	◦ Observe maintainer actions to absorb unspoken rules.
• What kinds of contributions should you look for?
	◦ Small changes.
	◦ Provably correct changes.
	◦ Housekeeping tasks.
	◦ Changes with high public demand.
	◦ Not a refactoring.
• Exercises to build familiarity:
	◦ Review merged pull requests to understand successful bright spots.
	◦ Review closed (unmerged) pull requests for patterns to avoid.
	◦ Review “old” issues for patterns that might prevent successfully closing an issue.
	◦ Review “new” issues to see which types of changes get the most time and attention from maintainers.
	◦ Seek out positive role models of the maintainers you would like to emulate.
• COIL framework for contributions:
	◦ Context: Find problems through observation.
	◦ Opportunity: Brainstorm ways to solve those problems.
	◦ Implementation: Write the code, file the issue, or make the change.
	◦ Loop: Repeat the process until it’s done. Zoom-in or zoom-out as needed.

> Delist the repo from the site.

I don't want to take away whatever value the other 99 people currently signed up for this repo might be receiving

> When triaging, mention that the repo was listed on CodeTriage, so the maintainers can possibly share their stance on being listed there.

I've not seen this as a helpful pattern. The conversation got side-tracked and it took up additional maintainer time as a result.

> Create a way to flag/tag repos that don't need help in some way so the users can relay such information to each other without requiring intervention from the CodeTriage maintainers.

That's more interesting to me. The core of CodeTriage was basically asking "how can we do more, with less maintainer intervention." My general worries are how do we do this in a way that's also helpful to other triagers. While your takeaway here might be "they don't want help" my view is that they're (initially) saying they don't need arbitrary contextless help. So perhaps my warning to other contributors would be something like "this project is well staffed and maintainers have issues under control, take care before posting." (or something). 

I think there's something here for sure, I'm just not confident I know what a good user experience would be for it.

**Comment by kotp** [comment]
@schneems thank you for clarifying points about this project and how it addresses bringing attention to potentially (and often) open to help repositories, and how to find out about appropriate ways to gain the information to successfully engage.

I am familiar with the CodeTriage project, and know that it has the Exercism project in general in its target area.  I think that is perfectly fine, so no reason to delist it.

Your interpretation in the second to last paragraph (inside "details collapsable section) about "well staffed" is only secondary, in that many tracks are taking a break from contributions to help avoid exhaustion in the volunteer (and staff) team.

The summary of this message is really "Thank you for encouraging and making issues more visible in general for open source projects! (on github)."

And, for @scheals, definitely thank you for trying to carry the issues that you perceive to actionable change!

**Comment by iHiD** [comment]
Just to add even more noise here...

It's worth noting that Exercism is an extremely weird and unusual open source project. We have nearly 400 repos with different maintainers across them all, some central repos, some that are entirely closed off from contributors and some that entirely rely on them. It is, in other words, a total mess. And we also have a huge issue with burnout, which has led to us effectively giving our maintainers a semi-enforced 6 months off (read [my blog post](https://exercism.org/blog/freeing-our-maintainers) if you're interested).

One of the biggest issues I face in open-source, and I believe others face too, is noise-to-signal ratio. The definite biggest source of burnout for maintainers is people trying to be helpful but making more work for maintainers (and wasting their own energy) doing work that's not required or work that's not done with the wider contextual knowledge needed. Often pull requests (PRs) to Exercism cause more reviewing/discussion work for a maintainer than if the maintainer had just done the PR themselves. The one thing I'm starting to feel is working with this is getting people to become involved in the **community** before contributing. (A less exemplar but still helpful alternative IMO would be to open an issue saying "I'd love to help. I have 4 hours per week. Where can I be useful?" so the maintainer can then triage that energy wisely). For Exercism we have an active community on our forums who explore issues and ideas, and where we're finding great contributors through that. So maybe if you're looking for projects to get involved with, starting in their Forums/Discords/Slacks/whatever would be a great starting point - and if those don't exist, opening the issue to see where you can add value first.

I'm not sure if this is in keeping with @CodeTriage's way of working, but I thought it was worth sharing some thoughts here in case it inspires some good guidelines etc.

---

One practical note, I always find it worth checking who in a conversation is an org-member before posting. Viewing @kotp's GitHub profile would show you that he's a member of Exercism's org, which would also inform you that he probably knows what he's doing. That's saved me from embarrassment on multiple occasions. Again, maybe that's a useful suggestion to add to CodeTriage docs etc?

---

> I actually think you incidentally raised a really good point about the README

I entirely concur! I'd been wondering why people kept opening issues in this repo despite it being deprecated and you discovered it, which was high value to me and will save lots of people time and effort. So thank you for that! 🙂

---

Finally, thank y'all for wanting to help Exercism and open source in general 💙

**Comment by scheals** [comment]
@schneems Thank you very much for your feedback, read it thoroughly couple of times and really appreciate it. Not much I can add, my fault for jumping the gun.

@kotp @iHiD Once again, thank you for a very amicable interaction and your feedback. 

Based on all this, I'll move on to just observing repos for now.
