### ISSUE TITLE
Incorrect heading in hacktoberfest home page.

### ISSUE THREAD

**Issue by Ankitchaudharyy** [codetriage/CodeTriage#1798]
Incorrect heading in https://www.codetriage.com/topics/hacktoberfest page. 

## Expected Behavior
It should be ``` All repo with label hacktoberfest. ```

## Current Behavior
Currently it is : ``` All repo with with label hacktoberfest. ``` 
Refer to the green highlighted part in the image attached.

## Steps to Reproduce (for bugs)
Open this link : https://www.codetriage.com/topics/hacktoberfest page. 

<img width="2050" alt="Screenshot 2023-10-14 at 10 48 18 AM" src="https://github.com/codetriage/CodeTriage/assets/46367738/aa35287f-eff8-4dfe-b625-b1dbdccee094">

**Comment by Mattherix** [comment]
Thanks for the fix @Ankitchaudharyy. Since your pull request has been merged, could you close this issue ?

Please note that you can automatically close an issue by [linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
