### ISSUE TITLE
Send triage email based on time preference

### ISSUE THREAD

**Issue by alksl** [codetriage/codetriage#244]
It would be nice to be able to set a preference when the triage email is sent out. For now it's problematic if you are in a different timezone.

I looked around in the source but I could't find where the emails are sent out. Some pointers would be helpful.

**Comment by elliotthilaire** [comment]
I receive emails at 5pm which is about the time I make sure my inbox is clear.
I would like to be able to set the time of day I receive the emails so they arrive when I am most motivated (for me, in the morning).

As this is an old issue. I want to ask before starting; Is this worth exploring?

**Comment by prathamesh-sonpatki** [comment]
Good idea :+1:

**Comment by elliotthilaire** [comment]
I've started work on this over at https://github.com/elliotthilaire/codetriage/tree/add-email-time-of-day-preference

The idea being that a person can select a preferred time of day from a dropdown box with 24 values.  [...,5:00am UTC, 6:00am UTC,...] etc.

We have a EmailDecider class that is used like this:
https://github.com/codetriage/codetriage/blob/master/app/models/user.rb#L123:L133

I am thinking of modifying this so that the Heroku schedular can run the email task hourly, and EmailDecider will cause a will skip if the current time of day is before the persons preferred time of day. (EmailDecider should take take of skipping if a person has already received today's email).
