### ISSUE TITLE
Please provide on_worker_boot examples for Postgres, Redis, and Memcache

### ISSUE THREAD

**Issue by monfresh** [codetriage/codetriage#310]
Hi,

Now that you are recommending Puma over Unicorn, I started reading [this article](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server) where you mention that "You will need to re-connect to any datastore such as Postgres, Redis, or memcache". Yet, you only provide an example for Resque.

I haven't been able to find any documentation for the proper way to reconnect to those datastores, so it would be greatly appreciated if you could add that to the documentation and this example repo's `config/puma.rb`.

Thanks!

**Comment by LucasCioffi** [comment]
@monfresh Did you ever get an answer to this question?  I'm looking for the Postgres answer.

**Comment by schneems** [comment]
Take a look at https://github.com/codetriage/codetriage/blob/323577bec1a9ffec1d39d76da1b7dce6e2610469/config/puma.rb#L11-L16 

It will show you how to disconnect from ActiveRecord (which will reconnect automatically). If you're using a different library to connect to postgres, then you would need to check the individual docs. Sidekiq doesn't need to be disconnected since it doesn't connect until it tries to do work. Memcache in our project is also lazily connected.

**Comment by LucasCioffi** [comment]
Thank you @schneems.
