### ISSUE TITLE
Provide helpful errors for invalid input when adding new repos

### ISSUE THREAD

**Issue by O-I** [codetriage/codetriage#314]
I think this is a separate issue from #241, but feel free to close if you think it's a duplicate or not worth worrying about at this stage.

Currently, entering any sort of invalid input into any of the form fields on `repos/new` and submitting throws up a 422 or 500 error. This includes scenarios like accidentally clicking 'Add Repo' before one or more form fields are completed, pasting in a malformed link, and even trying to add a repo you already triage.

Ideally, it would be nice if, instead of the app blowing up, the page was re-rendered with helpful errors like "those fields can't be blank" or "this repo doesn't seem to exist; you may have mistyped something" or "you're already triaging this repo".

Most of these scenarios are pretty unlikely so it's not that big of a deal, but I'm all for more foolproof forms if it all possible.

**Comment by chrisccerami** [comment]
Hey I took a shot at submitting a pull request for this issue, #333. It's my first real open source contribution, so let me know if anything needs to be cleaned up. I'm not sure if the previous functionality was intentional, but considering the controller does have code to re-render the page on failure, I assume that's the intended result.

**Comment by schneems** [comment]
Closed via #333. It's merged in, should auto-deploy in a few minutes. Give it a whirl maybe in 30 min and let me know if that works for you, if not i'll re-open issue. Thanks for the report and the fix :heart:
