### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by schneems** [codetriage/codetriage#413]
Hey @olivierlacan i've got some questions badges and http://shields.io/. 

How exactly am I supposed to use shields.io? Should I generate the shields.io url and return a 301 from my own server to point at that URL? Should I query the shields url and separately return the svg string? 

It looks like the badge for code climate is somehow making a request to another server for a value https://img.shields.io/codeclimate/github/codetriage/codetriage.svg how did they set that up? Would it be recommended to do something like that?

Another alternative would be to take the template svg provided by shields, modify the string in a Rails endpoint and return that value. Then I don't have to worry about overloading shields.io server with extra traffic. Though then I would worry about making sure my server is responsive for serving the results.

Any idea what others do like travis or code climate?

**Comment by olivierlacan** [comment]
People do it differently. 

I think the most common approach is caching. Since Code Climate knows when the badge should change they can generate a new one from Shields only when necessary. But that's my guess, it's been a while since I talked to @brynary about it. I think the img.shields.io server is set up to handle heavy traffic but maybe talk to @espadrine before first to make sure there's not a better way.

Service-provider implementation documentation is definitely something we could add to shields.io.

**Comment by espadrine** [comment]
> Should I generate the shields.io url and return a 301 from my own server to point at that URL?

A 301 is usually inadequate, as most badge services feature temporary information.

The usual execution of a badge request is to compute what you want the badge to show and to call shields.io by fetching a badge from `/badge/`, inserting in the information (eg. `https://img.shields.io/badge/issues-10-brightgreen.svg` yields ![](https://img.shields.io/badge/issues-10-brightgreen.svg)), and returning the image to the client. If you have a countable set of possible badges (such as Travis' `passed` / `failed` / `pending`), I suggest using a cache, updated weekly (badge designs usually don't change all that often, but they can change, for example to fix a rendering issue on a device).

I recommend supporting special parameters that we support by simply passing them along to us, such as `?style=…` (the most asked for) and `?label=…`.

**Comment by schneems** [comment]
I opened up a PR with an implementation here: https://github.com/codetriage/codetriage/pull/414. It seems a bit kludgy to call out to shields.io like that. I would think that rendering svg by a library like a Ruby gem would be faster than a network call, though we are making it very infrequently due to caching. 

Would love to get your thoughts on that PR.

**Comment by espadrine** [comment]
We recommend using descriptive, non-branded nouns, in lowercase, on the left-hand-side of the badge. For instance, `build`, `coverage`, `downloads`, …

Apart from that, lgtm.

**Comment by schneems** [comment]
Interesting. Why lowercase?

I'm displaying "code triage subscribers to this repo" but that's a bit long. I don't want to say "subscribers" as that could get confused with Github's watchers. Maybe just "triage" or "triagers"?

**Comment by olivierlacan** [comment]
@schneems Lowercase because it fits the badge's purpose as a compact single `key => value` store. It's very much a poetry-style restriction but it's always great because when people do find the term that best summarizes the information provided by the badge, the information carried by one or more Shields badges is extremely dense.

I think these would work great:

![](https://img.shields.io/badge/triagers-407-red.svg)

![](https://img.shields.io/badge/issue_triagers-321-red.svg)

![](https://img.shields.io/badge/code_triagers-235-red.svg)

Here's what it would look like in context for the `t` gem for instance:

[![Gem Version](https://img.shields.io/gem/v/t.svg)](https://rubygems.org/gems/t) [![Build Status](https://img.shields.io/travis/sferik/t.svg)](https://travis-ci.org/sferik/t) [![Dependency Status](https://img.shields.io/gemnasium/sferik/t.svg)](https://gemnasium.com/sferik/t) [![Coverage Status](https://img.shields.io/coveralls/sferik/t.svg)](https://coveralls.io/r/sferik/t) [![Issue Triagers](https://img.shields.io/badge/code_triagers-235-red.svg)](http://www.codetriage.com/sferik/t)
