### ISSUE TITLE
Stop making me choose between daily emails or deleting my account

### ISSUE THREAD

**Issue by wolftune** [codetriage/codetriage#458]
I am inclined to say aggressive things to express how atrocious and obnoxious I feel this is, how angry I am about this. Maybe CodeTriage is too minor a project to even care about, but… it's absolutely terrible that you made a system that requires daily emails or nothing. You don't know how I use my email. Let me use CodeTriage the way I want and let me turn on and off emails whenever I wish (such as right now where I have to choose between deleting my CodeTriage account or dealing with daily emails when I have personal family things that make it impossible for me to get any value out of them for a while). Stop it. Let me turn off emails for now but keep my account.

**Comment by schneems** [comment]
It doesn't do daily emails. It has a back-off if you're not using it. https://github.com/codetriage/codetriage/blob/1d8724a5d9eaeab2357f4e3436197c20e5076486/app/models/email_decider.rb#L36-L47

If you're interested in adding a feature to let you set the minimum frequency i.e. daily/weekly/every-other-week, i'm happy to work with you.

**Comment by schneems** [comment]
Alternatively it sounds like you're asking for a OOO feature, that would keep your settings but not email you for an extended period. That could be a good feature if you're interested in implementing.

**Comment by wolftune** [comment]
bluntly: I'm a new father just a bit annoyed at seeing emails bugging me to delete my account and settings as the only way to pause the emails; and I have no possibility of contributing any time soon, although no offense in being asked. cheers

**Comment by GustavoCaso** [comment]
@schneems I'll be happy to work on the feature for setting the minimum frequency

**Comment by schneems** [comment]
So i've been thinking about this and I think the easiest way is to let people choose their "default" email setting. Basically instead of defaulting to `:daily` here, let people pick between daily, weekly or twice a week https://github.com/codetriage/codetriage/blob/86c2f1e04a46f3b351b9029acafa5c75c6832865/app/models/email_decider.rb#L38. We could store that in the DB for each user and use that setting when present.

People would still get the exponential backoff feature when they get busy but at least it lets you tone down the volume of emails easily.

**Comment by GustavoCaso** [comment]
Great @schneems so I will implement it ASAP !

**Comment by schneems** [comment]
This was implemented in #472 thanks!
