### ISSUE TITLE
Star counts  of repo not appear on main page.

### ISSUE THREAD

**Issue by SagareGanesh** [codetriage/codetriage#510]
@schneems please see this [PR](https://github.com/codetriage/codetriage/pull/504#issuecomment-242930184). In this PR I have added a Star conut feature. This PR contains 2 migrations which we have to run on production. Please run these migration if not so this will resolve [star count broken issue](https://github.com/codetriage/codetriage/commit/33088ffc4d5c3a2b901c11b37d65fbc991d12f32).

**Comment by schneems** [comment]
The star feature was responsible for the website not deploying for almost 30 days. I already ran the migrations.

I am opting to remove it instead. The visual style doesn't mesh well with the rest of the site. Here's the commit where I removed it https://github.com/codetriage/codetriage/commit/33088ffc4d5c3a2b901c11b37d65fbc991d12f32 but since deploys are failing, it hasn't been deployed yet.

**Comment by schneems** [comment]
Ahh, the deploy did work. But formatting is still messed up.

**Comment by SagareGanesh** [comment]
@schneems On locally its working correctly. please see
![codetriage1](https://cloud.githubusercontent.com/assets/16730632/19350020/b45246a2-9173-11e6-8644-7a9f882212ba.jpg)
Also I had discussed formatting with @prathamesh-sonpatki in this [PR](https://github.com/codetriage/codetriage/pull/504#issuecomment-242930184).
Still there is any issue in formatting, I will resolve it.

**Comment by prathamesh-sonpatki** [comment]
@SagareGanesh  If you are interested please resolve https://monosnap.com/file/GABAV9A4QQiUgkipuDWrwp0ZoIu7Ur 

Thanks :smile:

**Comment by SagareGanesh** [comment]
@prathamesh-sonpatki I have resolved https://monosnap.com/file/GABAV9A4QQiUgkipuDWrwp0ZoIu7Ur.
please look into pr.
