### ISSUE TITLE
Somehow Devise templates are getting rendered, which don't exist

### ISSUE THREAD

**Issue by nateberkopec** [codetriage/codetriage#580]
https://sentry.io/share/issue/3137333132372e323835303035373332/

**Comment by nateberkopec** [comment]
One way to repro is to visit /sidekiq if youre not an admin.

**Comment by foxycoder** [comment]
The problem is not that templates are getting rendered, it is that Devise has a shared partial that renders a link to `new_registration_path` because the User model has [`devise :registerable`](https://github.com/codetriage/codetriage/blob/master/app/models/user.rb#L4), but the routes config has [`devise_for :users, skip: [:registration]`](https://github.com/codetriage/codetriage/blob/master/config/routes.rb#L16).

Removing `devise :registerable` from the model should fix this problem. Users will still be able to sign up through their Github accounts by means of `devise :omniauthable`.

If that introduces too much of a problem for other parts of the app and/or tests, you could override the `devise/shared/_links.html.erb` template and remove the registration link.

**Comment by schneems** [comment]
Is there a downside? Seems good. Can you send a PR?

**Comment by foxycoder** [comment]
@schneems happy to, but for which of the 2 solutions? 😄

**Comment by schneems** [comment]
Oh. Right. The only way I currently expose users to sign up is via github, so disabling `devise :registerable` should be fine.

**Comment by nateberkopec** [comment]
> Is there a downside? Seems good. Can you send a PR?

@schneems got caught using his issue autoresponder 😆

**Comment by foxycoder** [comment]
Haha!

Done. Let me know if this works for you.

**Comment by schneems** [comment]
LOL, should totally build that, just comment on every issue:

> Is there a downside? Seems good. Can you send a PR?
