### ISSUE TITLE
is it possible to support gitlab

### ISSUE THREAD

**Issue by jlozadad** [codetriage/codetriage#613]
although a lot of projects are on github, they are still cool ones in gitlab. Is it possible to support it?

**Comment by schneems** [comment]
The short answer is not really. The longer answer is that this is a free service maintained for free by volunteers (including me) and there's really no resources to support other services.

This app heavily relies on the GitHub api. We have to crawl issues, save them in the database. Then before we send out emails we need to use the API to make sure we're not sending you an issue you've already commented on, or that you opened, and we make one final check to verify the issue is still open. All of these are API calls.

Supporting a new backend would require new API clients, and logic for all these calls. It's not an insurmountable amount of work, but it is a LOT of work, and there's just not enough resources. It also means any new feature development go from writing the logic once to writing it for N supported backends.

If you really want a non-github project to be supported on CodeTriage the easiest thing to do would probably be make an importer so that we could say migrate bitbucket or gitlab issues to a github repo and keep the two in sync. Then add that github repo to CodeTriage.
