### ISSUE TITLE
Source links are broken

### ISSUE THREAD

**Issue by ragesoss** [codetriage/codetriage#646]
Every link for my project that I've clicked from codetriage is a 404.

For example, https://www.codetriage.com/doc_methods/353453

The source link goes to https://github.com/wikieducationfoundation/wikiedudashboard/blob/6f95bf57b52e382f7212723fb5a9daace5271743/#L65

**Comment by schneems** [comment]
It looks like that's a valid SHA https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/6f95bf57b52e382f7212723fb5a9daace5271743

However it needs a file too.

It looks like this is due to the way that i'm generating the file name. 

i'm downcasing the repo names but not the file url

```
irb(main):016:0>     _absolute, _match, relative = raw_file.partition(/(\/|^)#{repo.name}\//)
=> ["/tmp/d20171121-4-ncqlpn/WikiEduDashboard/app/models/classroom_program_course.rb", "", ""]
irb(main):017:0> repo.name
=> "wikiedudashboard"
```

Patch is incoming

**Comment by schneems** [comment]
Fixed, we've got auto deploy enabled with passing builds on master, should be live in 30 minutes or so.
