### ISSUE TITLE
No option to unsubscribe to emails

### ISSUE THREAD

**Issue by sebasrp** [codetriage/codetriage#710]
There is no option to completely opt out from emails - the only option is to delete the account, which i grumpily just did.

I believe codetriage should allow the unsubscription from emails without the need to delete the account.
This is something that is also required for the GDRP compliance.

**Comment by kwugirl** [comment]
I don't know much about the details of what's required for GDRP compliance, but I was just going through setting up an account myself and it seems like you might be able to unsubscribe via setting your max limit of issues to receive per day to 0?

![image](https://user-images.githubusercontent.com/3782112/41250507-22b565ae-6d85-11e8-9310-1e34c8222477.png)

**Comment by schneems** [comment]
The only purpose of the app is to send emails. Unsubscribing would be effectively deleting your account. What would you hope to do via unsubscribing versus unsubscribing?

@kwugirl good hack! That’s not intentional but definetly would work for now.

**Comment by mattzollinhofer** [comment]
Yeah, the whole point of the app is to send emails. There’s probably a non zero maintenance burden to keeping unused accounts around forever as well (even though that’s fairly common in a lot of apps). But you probably have big VC money in the bank to hire some more help :laugh:

If this goes against the app’s philosophy then it seems like the issue can be closed.

**Comment by ZainRizvi** [comment]
Another option: Offer an unsubscribe button but have that really just delete the account on the backend. Because if someone has stopped working on this project and the emails start feeling like spam then it prob best to just give them a nice and easy out.

Alternative option: Actively delete accounts that have had 0 email subscriptions over the past X months (you probably have a significant number of those people in your database already)

**Comment by schneems** [comment]
It would be confusing to "unsubscribe" then come back and find all your settings are gone and you're no longer following repos.
