### ISSUE TITLE
Random repo in user mailer can sometimes be nil

### ISSUE THREAD

**Issue by nateberkopec** [codetriage/codetriage#801]
This randomly fails on tests and in prod. 

[Problem is this line.](https://github.com/codetriage/codetriage/blob/master/app/mailers/user_mailer.rb#L78)

**Comment by GabrielRMuller** [comment]
Hey! I was taking a look at this test and the reason it was failing was probably because sometimes there wasn't a repo that wasn't in both `@most_repo` and `@need_repo`, so using `not_in` to search for one was the cause of the `nil` in `@random_repo`. 

To fix this I removed `not_in`and now it searches for a random repo using only `rand` (also I fixed a small typo on the `repo.rb` file). Take a look! #909

**Comment by prathamesh-sonpatki** [comment]
Closed by #909
